//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _01.SERVIDOR.ec.edu.monster.modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class factura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public factura()
        {
            this.detalle_factura = new HashSet<detalle_factura>();
        }
    
        public string FAC_CODIGO { get; set; }
        public string CLI_ID { get; set; }
        public System.DateTime FAC_FECHA_EMISION { get; set; }
        public decimal FAC_SUBTOTAL { get; set; }
        public decimal FAC_VALOR_IVA { get; set; }
        public decimal FAC_TOTAL { get; set; }
        public int FAC_ID { get; set; }
    
        public virtual cliente cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_factura> detalle_factura { get; set; }
    }
}
