//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary1.ec.edu.monster.modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class localidad_partido
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public localidad_partido()
        {
            this.detalle_factura = new HashSet<detalle_factura>();
        }
    
        public int LOC_ID { get; set; }
        public int PAR_ID { get; set; }
        public int TIPL_ID { get; set; }
        public decimal LOC_PRECIO { get; set; }
        public int LOC_DISPONIBILIDAD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_factura> detalle_factura { get; set; }
        public virtual partido_futbol partido_futbol { get; set; }
        public virtual tipo_localidad tipo_localidad { get; set; }
    }
}
